# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ddebr/Verilog/stopwatch/stopwatch.srcs/sources_1/ip/ip_clk_div/ip_clk_div.xci
# IP: The module: 'ip_clk_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ddebr/Verilog/stopwatch/stopwatch.gen/sources_1/ip/ip_clk_div/ip_clk_div_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_clk_div'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ddebr/Verilog/stopwatch/stopwatch.gen/sources_1/ip/ip_clk_div/ip_clk_div.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ddebr/Verilog/stopwatch/stopwatch.gen/sources_1/ip/ip_clk_div/ip_clk_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/ddebr/Verilog/stopwatch/stopwatch.srcs/sources_1/ip/ip_clk_div/ip_clk_div.xci
# IP: The module: 'ip_clk_div' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ddebr/Verilog/stopwatch/stopwatch.gen/sources_1/ip/ip_clk_div/ip_clk_div_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ddebr/Verilog/stopwatch/stopwatch.gen/sources_1/ip/ip_clk_div/ip_clk_div.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ddebr/Verilog/stopwatch/stopwatch.gen/sources_1/ip/ip_clk_div/ip_clk_div_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_clk_div'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
