



set_property IOSTANDARD LVCMOS33 [get_ports {led_disable[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_disable[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_disable[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_disable[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_disable[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_disable[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_enable[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_enable[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num_2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_main]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN N4 [get_ports {led_disable[5]}]
set_property PACKAGE_PIN N2 [get_ports {led_disable[4]}]
set_property PACKAGE_PIN N5 [get_ports {led_disable[3]}]
set_property PACKAGE_PIN M3 [get_ports {led_disable[2]}]
set_property PACKAGE_PIN M6 [get_ports {led_disable[1]}]
set_property PACKAGE_PIN N6 [get_ports {led_disable[0]}]
set_property PACKAGE_PIN M1 [get_ports {led_enable[1]}]
set_property PACKAGE_PIN L1 [get_ports {led_enable[0]}]
set_property PACKAGE_PIN R6 [get_ports {num_1[3]}]
set_property PACKAGE_PIN R7 [get_ports {num_1[2]}]
set_property PACKAGE_PIN U8 [get_ports {num_1[1]}]
set_property PACKAGE_PIN U9 [get_ports {num_1[0]}]
set_property PACKAGE_PIN P4 [get_ports {num_2[3]}]
set_property PACKAGE_PIN P3 [get_ports {num_2[2]}]
set_property PACKAGE_PIN R3 [get_ports {num_2[1]}]
set_property PACKAGE_PIN T1 [get_ports {num_2[0]}]
set_property PACKAGE_PIN L6 [get_ports {sev_seg_leds[7]}]
set_property PACKAGE_PIN M2 [get_ports {sev_seg_leds[6]}]
set_property PACKAGE_PIN K3 [get_ports {sev_seg_leds[5]}]
set_property PACKAGE_PIN L4 [get_ports {sev_seg_leds[4]}]
set_property PACKAGE_PIN L5 [get_ports {sev_seg_leds[3]}]
set_property PACKAGE_PIN N1 [get_ports {sev_seg_leds[2]}]
set_property PACKAGE_PIN L3 [get_ports {sev_seg_leds[1]}]
set_property PACKAGE_PIN M4 [get_ports {sev_seg_leds[0]}]
set_property PACKAGE_PIN E3 [get_ports clk_main]
set_property PACKAGE_PIN E16 [get_ports reset]
